//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Routing.Domain.Test.BancaSella {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://ecomm.sella.it/", ConfigurationName="BancaSella.WSCryptDecryptSoap")]
    public interface WSCryptDecryptSoap {
        
        // CODEGEN: Generating message contract since element name shopLogin from namespace https://ecomm.sella.it/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="https://ecomm.sella.it/Encrypt", ReplyAction="*")]
        Routing.Domain.Test.BancaSella.EncryptResponse Encrypt(Routing.Domain.Test.BancaSella.EncryptRequest request);
        
        // CODEGEN: Generating message contract since element name shopLogin from namespace https://ecomm.sella.it/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="https://ecomm.sella.it/Decrypt", ReplyAction="*")]
        Routing.Domain.Test.BancaSella.DecryptResponse Decrypt(Routing.Domain.Test.BancaSella.DecryptRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EncryptRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Encrypt", Namespace="https://ecomm.sella.it/", Order=0)]
        public Routing.Domain.Test.BancaSella.EncryptRequestBody Body;
        
        public EncryptRequest() {
        }
        
        public EncryptRequest(Routing.Domain.Test.BancaSella.EncryptRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://ecomm.sella.it/")]
    public partial class EncryptRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string shopLogin;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string uicCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string amount;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string shopTransactionId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string cardNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string expiryMonth;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string expiryYear;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string buyerName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string buyerEmail;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string languageId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string cvv;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string customInfo;
        
        public EncryptRequestBody() {
        }
        
        public EncryptRequestBody(string shopLogin, string uicCode, string amount, string shopTransactionId, string cardNumber, string expiryMonth, string expiryYear, string buyerName, string buyerEmail, string languageId, string cvv, string customInfo) {
            this.shopLogin = shopLogin;
            this.uicCode = uicCode;
            this.amount = amount;
            this.shopTransactionId = shopTransactionId;
            this.cardNumber = cardNumber;
            this.expiryMonth = expiryMonth;
            this.expiryYear = expiryYear;
            this.buyerName = buyerName;
            this.buyerEmail = buyerEmail;
            this.languageId = languageId;
            this.cvv = cvv;
            this.customInfo = customInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EncryptResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EncryptResponse", Namespace="https://ecomm.sella.it/", Order=0)]
        public Routing.Domain.Test.BancaSella.EncryptResponseBody Body;
        
        public EncryptResponse() {
        }
        
        public EncryptResponse(Routing.Domain.Test.BancaSella.EncryptResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://ecomm.sella.it/")]
    public partial class EncryptResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.XmlElement EncryptResult;
        
        public EncryptResponseBody() {
        }
        
        public EncryptResponseBody(System.Xml.XmlElement EncryptResult) {
            this.EncryptResult = EncryptResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DecryptRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Decrypt", Namespace="https://ecomm.sella.it/", Order=0)]
        public Routing.Domain.Test.BancaSella.DecryptRequestBody Body;
        
        public DecryptRequest() {
        }
        
        public DecryptRequest(Routing.Domain.Test.BancaSella.DecryptRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://ecomm.sella.it/")]
    public partial class DecryptRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string shopLogin;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string CryptedString;
        
        public DecryptRequestBody() {
        }
        
        public DecryptRequestBody(string shopLogin, string CryptedString) {
            this.shopLogin = shopLogin;
            this.CryptedString = CryptedString;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DecryptResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DecryptResponse", Namespace="https://ecomm.sella.it/", Order=0)]
        public Routing.Domain.Test.BancaSella.DecryptResponseBody Body;
        
        public DecryptResponse() {
        }
        
        public DecryptResponse(Routing.Domain.Test.BancaSella.DecryptResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://ecomm.sella.it/")]
    public partial class DecryptResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.XmlElement DecryptResult;
        
        public DecryptResponseBody() {
        }
        
        public DecryptResponseBody(System.Xml.XmlElement DecryptResult) {
            this.DecryptResult = DecryptResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSCryptDecryptSoapChannel : Routing.Domain.Test.BancaSella.WSCryptDecryptSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSCryptDecryptSoapClient : System.ServiceModel.ClientBase<Routing.Domain.Test.BancaSella.WSCryptDecryptSoap>, Routing.Domain.Test.BancaSella.WSCryptDecryptSoap {
        
        public WSCryptDecryptSoapClient() {
        }
        
        public WSCryptDecryptSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSCryptDecryptSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSCryptDecryptSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSCryptDecryptSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Routing.Domain.Test.BancaSella.EncryptResponse Routing.Domain.Test.BancaSella.WSCryptDecryptSoap.Encrypt(Routing.Domain.Test.BancaSella.EncryptRequest request) {
            return base.Channel.Encrypt(request);
        }
        
        public System.Xml.XmlElement Encrypt(string shopLogin, string uicCode, string amount, string shopTransactionId, string cardNumber, string expiryMonth, string expiryYear, string buyerName, string buyerEmail, string languageId, string cvv, string customInfo) {
            Routing.Domain.Test.BancaSella.EncryptRequest inValue = new Routing.Domain.Test.BancaSella.EncryptRequest();
            inValue.Body = new Routing.Domain.Test.BancaSella.EncryptRequestBody();
            inValue.Body.shopLogin = shopLogin;
            inValue.Body.uicCode = uicCode;
            inValue.Body.amount = amount;
            inValue.Body.shopTransactionId = shopTransactionId;
            inValue.Body.cardNumber = cardNumber;
            inValue.Body.expiryMonth = expiryMonth;
            inValue.Body.expiryYear = expiryYear;
            inValue.Body.buyerName = buyerName;
            inValue.Body.buyerEmail = buyerEmail;
            inValue.Body.languageId = languageId;
            inValue.Body.cvv = cvv;
            inValue.Body.customInfo = customInfo;
            Routing.Domain.Test.BancaSella.EncryptResponse retVal = ((Routing.Domain.Test.BancaSella.WSCryptDecryptSoap)(this)).Encrypt(inValue);
            return retVal.Body.EncryptResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Routing.Domain.Test.BancaSella.DecryptResponse Routing.Domain.Test.BancaSella.WSCryptDecryptSoap.Decrypt(Routing.Domain.Test.BancaSella.DecryptRequest request) {
            return base.Channel.Decrypt(request);
        }
        
        public System.Xml.XmlElement Decrypt(string shopLogin, string CryptedString) {
            Routing.Domain.Test.BancaSella.DecryptRequest inValue = new Routing.Domain.Test.BancaSella.DecryptRequest();
            inValue.Body = new Routing.Domain.Test.BancaSella.DecryptRequestBody();
            inValue.Body.shopLogin = shopLogin;
            inValue.Body.CryptedString = CryptedString;
            Routing.Domain.Test.BancaSella.DecryptResponse retVal = ((Routing.Domain.Test.BancaSella.WSCryptDecryptSoap)(this)).Decrypt(inValue);
            return retVal.Body.DecryptResult;
        }
    }
}
